### ISSUE TITLE
Unwanted delay when using swap()

### ISSUE THREAD

**Issue by Lootwig** [gskinner/flutter_animate#102]
When running [this code](https://dartpad.dev/?id=b2224f73129986afdc88b4d0b191ce6e), there is a noticeable delay when clicking the "swap" button until the red containers appear (tested in android emulator).

There is no delay when clicking swap again and the containers are removed (i.e. exchanged for the `shrink`s again).

The delay actually scales along with the "slow animations" feature.

Adding `delay: 0.ms` to either `animate()` or `swap()` doesn't change anything.

Is there another setting I am overlooking?

```
% flutter --version
Flutter 3.13.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision efbf63d9c6 (13 days ago) • 2023-08-15 21:05:06 -0500
Engine • revision 1ac611c64e
Tools • Dart 3.1.0 • DevTools 2.25.0
```

**Comment by gskinner** [comment]
`SwapEffect` runs the swap at the end of its `duration`. By default it will use `Animate.defaultDuration` if one isn't specified.

As an aside, I wouldn't bother using Animate in the example you provided to swap the content, just return different content directly. Swap is intended to do the swap at a specified time, or as part of a larger animation.

**Comment by Lootwig** [comment]
Thanks for the feedback!
