### ISSUE TITLE
Color effect does not maintain decorations

### ISSUE THREAD

**Issue by DizzasTeR** [gskinner/flutter_animate#103]
```dart

Container(
  height: 30.h,
  decoration: ShapeDecoration(
    color: Colors.black12,
    shape: RoundedRectangleBorder(
      borderRadius: BorderRadius.circular(4))
  ),
  child: const Center(
    child: Icon(Icons.delete,
      size: 18, color: Colors.white70)
    ),
  )
).animate(target: dragIsOnTarget() ? 1 : 0).color(end: Colors.red)
```

Please notice the border in this example:

Before animation:
![image](https://github.com/gskinner/flutter_animate/assets/16344370/51594413-5c25-4586-873b-0c1d0e72ba04)

After animation:
![image](https://github.com/gskinner/flutter_animate/assets/16344370/b13052ff-b006-4b9a-83df-f7c224045a55)

Any help would be appreciated

**Comment by gskinner** [comment]
From the docs:
> [blendMode] defaults to [BlendMode.color]. Note that most blend modes in Flutter (including `color`) do not preserve the alpha channel correctly. See [BlendMode.srcATop] or [BlendMode.srcIn] for options that do maintain alpha.

I'd take a look at `TintEffect` instead. It will _probably_ do what you need.
