### ISSUE TITLE
FadeEffect with BlendMode in BoxDecoration crashes the app without any warnings

### ISSUE THREAD

**Issue by ginecode** [gskinner/flutter_animate#107]
```dart
Animate(
  effects: const [FadeEffect()],
  child: Container(
    width: 300,
    height: 300,
    decoration: BoxDecoration(color: Colors.white, backgroundBlendMode: BlendMode.difference),
  ),
),
```

**Comment by gskinner** [comment]
Interesting. That sounds like a low level Flutter bug to me if it's reproducible. `FadeEffect` is super simple (just uses a `FadeTransition`).

Maybe try to isolate and report to the engine team? Feel free to reopen if you narrow it down to Animate, but that seems unlikely to me.
