### ISSUE TITLE
Doesn't currently support SelectableText, SelectableText.rich and TextSpan

### ISSUE THREAD

**Issue by bradleydalina** [gskinner/flutter_animate#112]
error: The method 'animate' isn't defined for the type 'TextSpan'. (undefined_method )

I hope it can be supported

**Comment by gskinner** [comment]
`TextSpan` is not a widget, and cannot be wrapped in widgets (which is the core mechanism for Animate). Closing, but feel free to reopen if anyone has ideas on how this could be supported.
