### ISSUE TITLE
interval property no more avalaible in animate() since 4.3.0

### ISSUE THREAD

**Issue by ljoly83** [gskinner/flutter_animate#118]
interval property no more avalaible in animate() since 4.3.0 and the documentation not updated.
https://pub.dev/documentation/flutter_animate/4.3.0/flutter_animate/AnimateList-class.html
Please update and explain how to do then?

**Comment by gskinner** [comment]
<img width="588" alt="image" src="https://github.com/gskinner/flutter_animate/assets/157128/7a6b4389-3b86-4d19-b5b7-5f5c1a903cd0">
