### ISSUE TITLE
Can't get animation to run when calling set state

### ISSUE THREAD

**Issue by johnareid54** [gskinner/flutter_animate#121]
I have been trying to get the animation to run when set state is called, but for some reason the animation only runs when the page is loaded.

`myWidget.animate(target: _over ? 1 : 0).slideX(
                  duration: 500.ms,
                  begin: -1,
                  end: 0,
                ),`

The animate should slide the widget which is full screen from left to right.
I have searched everywhere for a working example of using the target, but the only code is in readme `MyButton().animate(target: _over ? 1 : 0)
  .fade(end: 0.8).scaleXY(end: 1.1)`
and there is no working example I can run and try.
I can cheat by defining an controller and calling controller.forward(from: -1); but this seems to be overcomplicated.
Any help would be appreciated.

**Comment by gskinner** [comment]
Here's a quick working example you can paste into `playground_view.dart`:

```
class PlaygroundView extends StatefulWidget {
  const PlaygroundView({Key? key}) : super(key: key);

  @override
  State<PlaygroundView> createState() => _PlaygroundViewState();
}

class _PlaygroundViewState extends State<PlaygroundView> {
  bool _val = false;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        const Text("Playground 🛝")
            .animate(target: _val ? 1 : 0)
            .slideY()
            .fadeIn(),
        IconButton(
          onPressed: () => setState(() => _val = !_val),
          icon: const Icon(Icons.arrow_circle_right, color: Colors.white),
        ),
      ],
    );
  }
}
```

**Comment by johnareid54** [comment]
Many thanks, the example works but how can I get it to always slide in, at the moment it will slide in when set state is called, but then slide out when set state is called again. I just want to it always begin at -1 and slide in.
