### ISSUE TITLE
animate has no property controller on widget list

### ISSUE THREAD

**Issue by ljoly83** [gskinner/flutter_animate#122]
I don't know if it's intentional or something to suggest, but when we apply <widget>.animate() and List<Widget>.animate(), we don't have the controller property on the list like for the single widget.
Is this normal?

**Comment by gskinner** [comment]
Yes, each item in the list has its own controller. I suppose it's conceivably possible to share a controller between multiple items, but it would break if you did anything that changed the total duration of any individual animation (including using `interval`).

Closing, but feel free to comment if you have critical use cases or additional thoughts.
