### ISSUE TITLE
Animate custom property with minimal boilerplate (Similar to Implict Widgets)

### ISSUE THREAD

**Issue by brijs** [gskinner/flutter_animate#124]
Hi, thanks for the awesome package! 

I am trying to figure out the best way to animate a custom `myProperty` on a widget.  In the example below, when `myProperty` changes (to say, 50), I'd like to animate `MyWidget` from 15 to 50, using a builder method.

```dart
MyWidget(
   myProperty :  15, // let's say its an Integer that can change arbtrarily, 
                     // and is something that is passed in by the parent
)
```

Animate's `custom` effect does work, but I think there is quite a bit of boilerplate still needed in order to properly handle widget updates to  `myproperty` while it is in the middle of an ongoing animation - Basically it seems that we'd need to replicate lot of what `ImplicitlyAnimatedWidgetState` does otherwise.

Here's what I think the implementation would look like:

```dart
//  State
Tween<int> _myPropertyTween = ...;
late Animation<double> _animationController; // hoisted from Animate()

// Initialize State
initState() {
  _myPropertyTween = Tween<int>(begin: widget.myProperty, end: widget.myProperty);
}
...
// handle widget update
didUpdateWidget(oldWidget) {
  // update Tween State
  _myPropertyTween
      ..begin = _myPropertyTween.evaluate(_animationController)
      ..end = widget.myProperty;
  }
  // reset controller
  _animationController
    ..reset()
    ..forward();
}

// Define animation
Animate( onInt: (controller) => _animationController = controller ) // hoist controller
  .custom(
    duration: 10.seconds,
    builder: (_, value, __) => 
      MyWidget(
        myProperty : _myPropertyTween.evaluate(animation), // build MyWidget with myProperty = 15 ... 50
      )
  );
```

Am I overcomplicating this? I have looked at `Animate().target` as well, but couldn't figure out a simpler way to do this.

Thank you

**Comment by brijs** [comment]
I figured a slightly better way to above by using a `TweenAnimationBuilder` which gives me exactly what I need without having to manage my own `AnimationController`. 

The downside is that I want to use `Animate` for any additional `effects`, these would be driven by 2 independent animation controllers (one inside `Animate`, and one inside `TweenAnimationBuilder`).


```dart
// animate my tween
TweenAnimationBuilder(
  tween: Tween<int>(end: widget.myProperty),
  duration: 1000.ms,
  builder: (context, tweeValue, _) {
    return MyWidget( myProperty : tweenValue);
  }
)
// .. and then use Animate & Effects, but uses a separate AnimationController
.animate()
.blur()
// ... other effects
```

**Comment by gskinner** [comment]
Flutter makes creating a generic solution to animating arbitrary properties difficult, and that's definitely not the core goal of Animate. However, I _think_ this comes close to what you want:

```
Animate(target: value / maxValue).custom(
  duration: 1000.ms,
  builder: (_, ratio, __) => MyWidget(myProperty: ratio * maxValue),
)
```

Unlike an implicit animation, this is bound to a range (0 -> maxValue), and will use a dynamic duration: where an implicit animation will take the same time to go from 0-->20 as 20-->100, the above approach will scale the duration with the delta.

> The downside is that if I want to use Animate for any additional effects, these would be driven by 2 independent animation controllers

You'd need separate controllers regardless if you're dealing with decoupled animations (ie. you're animating `myProperty` separately from the `blur`). If you wanted them synchronized, they could just be added like so:

```
Animate(target: value / maxValue).custom(
  duration: 1000.ms,
  builder: (_, ratio, __) => MyWidget(myProperty: ratio * maxValue),
).blur()
```

(as long as the blur duration wasn't longer than the custom duration)

Closing for now. Feel free to reopen or comment as appropriate.
