### ISSUE TITLE
The `flip` effect

### ISSUE THREAD

**Issue by fei1990** [gskinner/flutter_animate#135]
when i use the `flip` effect,  the reset() method can not work, 
<img width="849" alt="image" src="https://github.com/gskinner/flutter_animate/assets/20367597/c799bac3-d8aa-4fea-917a-f9734c29f23a">
how can i do?

**Comment by gskinner** [comment]
I just tested this, and it's working as expected for me (the full animation including the flip resets). Closing, feel free to reopen with more info if it remains an issue.
