### ISSUE TITLE
Can I use flutter_animate's shader to achieve the effect of gl-transition?

### ISSUE THREAD

**Issue by miluduo** [gskinner/flutter_animate#142]
How to write the transition between two widgets?
for example:https://gl-transitions.com/editor/directionalwarp

**Comment by gskinner** [comment]
It all depends on what you want to do, but for the example you posted we literally have a `ShaderEffect` that you can use arbitrary GL shaders with. For a simple cross fade, there's `CrossFadeEffect`.

**Comment by miluduo** [comment]
Sorry I didn't describe it clearly. 
Transition effects require two Textures, for example, CrossFadeEffect has a builder method to define the other one. But ShaderEffect can only work on one.

I wish there was something like https://pub.dev/packages/shader_presets.

**Comment by gskinner** [comment]
You can pass additional textures to the shader via the `ShaderEffect.update` callback. You could always abstract that to make capturing the second snapshot easier by creating a `CrossShaderEffect` or something like that.
