### ISSUE TITLE
Version `4.5.1` added `visibility_detector` dependency but its not used

### ISSUE THREAD

**Issue by absar** [gskinner/flutter_animate#143]
Version `4.5.1` added `visibility_detector` dependency but its not used

**Comment by gskinner** [comment]
Good catch. I removed it from the example, but didn't remember I had also added it to the library. Will publish a 4.5.2 shortly to address this.

**Comment by gskinner** [comment]
Done. 62c12040b1e3f80403b4fbfa48649155df006eb5
