### ISSUE TITLE
Add support for independant blurX / blurY

### ISSUE THREAD

**Issue by esDotDev** [gskinner/flutter_animate#19]
Sometimes it can be desirable to blur in a specific direction.

Maybe modify BlurEffect to take a `Offset`?

**Comment by gskinner** [comment]
We could do something similar to what's being discussed on #12 — modify the base `BlurEffect` to use an Offset, and then use extension methods to provide `blur` `blurX` `blurY` and `blurXY`.

**Comment by gskinner** [comment]
Resolved in 977dd80b19277a53457ff9c5b52e24b9965554ec
