### ISSUE TITLE
Allow pixel values for SlideEffect

### ISSUE THREAD

**Issue by sbis04** [gskinner/flutter_animate#21]
In the current `SlideEffect` implementation, it's possible to set the `begin` and `end` offsets only with **respect to the widget** width and height:

```dart
SlideEffect(
  duration: animInfo.duration.ms,
  begin: Offset(-1, 0),
  end: Offset(0, 0),
  curve: animInfo.curve,
)
```

So, in the above example, if the effect is applied on a widget having `height: 100` and `width: 100` then beginning `Offset(-1, 0)` signifies that the slide animation will start from 100 pixels to the left of the widget.

I believe there should be a way to allow setting the `begin` and `end` offsets in terms of raw **pixel values**,  so that we can use something like begin `Offset(-85, 0)` to signify the slide starts from 85 pixels left of the widget.

**Comment by gskinner** [comment]
@sbis04 — thanks for the feedback. This use case is handled by `MoveEffect`. I just pushed a small doc update that cross-links these two effects to make it easier to discover this.
