### ISSUE TITLE
Swaping a sequence of images and apply effects

### ISSUE THREAD

**Issue by xErik** [gskinner/flutter_animate#22]
Flutter Web

Running the code below, I am trying to swap a sequence of images and apply effects. 

However, due to `setState()` a new `animate` object gets initialized. Resulting in numerous calls to update the image after time. 
I was not able to cancel the old animation using `onComplete: (controller) => controller.stop()`, the number of calls keeps piling up.

I thought about leaving out `controller.repeat()` but then `nextImage()` gets never called. It is a bit of strange behavior. For me `onComplete` does not work consistently, I need to use `callback()` to call `nextImage()`.

Also tried to isolate everything in an `Animator` object in a semi-singleton, but then the current image gets not updated.

Also tried `swap()` but it did not work for me either.

Is there a correct approach to solve this?

Thank you!

```dart
class _FadeState extends State<Fade> {
  final c = ImageService();
  late Image img;

  @override
  initState() {
    super.initState();
    nextImage();
  }

  nextImage() {
    setState(() => img = c.nextImage());
  }

  @override
  Widget build(BuildContext context) {
    return Container(
            width: ..., height: ..., child: img)
        .animate(
          onPlay: ((controller) => controller.repeat()),
        )
        .tint(
            duration: c.crossFadeDuration.ms,
            color: c.color,
            begin: 1.0,
            end: 0.0)
        .then()
        .tint(
            duration: c.crossFadeDuration.ms,
            color: c.color2,
            begin: 0.0,
            end: 1.0)
        .callback(
            duration: c.crossFadeDuration.ms, callback: (_) => nextImage());
  }
}
```

**Comment by gskinner** [comment]
Glancing at this, I think it should work if you just get rid of the repeating, no? Right now the animation ends, spawns a brand new animation (via setState --> build), but also repeats itself. At some point the old animation should be disposed by Flutter, but I'm not sure what the timeframe is for that. Feel free to reopen if that doesn't resolve it.
