### ISSUE TITLE
Unable to stop animation using a provided `AnimationController`

### ISSUE THREAD

**Issue by pedromassango** [gskinner/flutter_animate#33]
Consider the following animation:

```dart
typedef ValueType = Article;

class AnimatedZoomImage extends StatelessWidget {
  const AnimatedZoomImage({
    Key? key,
    required this.scaleDuration,
    required this.animationController,
  }) : super(key: key);

  final Duration scaleDuration;
  
  
  final AnimationController animationController;

  @override
  Widget build(BuildContext context) {
    return CachedNetworkImage(
      fit: BoxFit.cover,
      imageUrl: 'some-url',
      alignment: Alignment.topCenter,
    ).animate(
      controller: animationController,
      onComplete: (c) => c.repeat(reverse: true),
    ).custom(
        duration: scaleDuration,
        builder: (context, value, child) {
          final scale = 1.0 + (value * .5);
          return Transform(
            alignment: Alignment.center,
            transform: Matrix4.identity().scaled(scale, scale, scale),
            child: child,
          );
        });
  }
}
```

Calling `animationController.stop()` does not stop the animation from running aka the builder method is still being called, is that by design?

**Comment by gskinner** [comment]
I just tested this, and it worked fine for me. Are you sure nothing is causing this view to be rebuilt with a new controller? As an aside, I'd consider moving the `repeat` call into `onPlay` instead of `onComplete`, as it's less likely to encounter a race condition (which may be what's happening, but I can't think of an obvious way for that to cause an issue).

One other thing you might run into, is if the `stop` is called synchronously with constructing the animation (or before the next tick IIRC), then it will occur _before_ Animate calls `forward` on the controller, which could also be causing your issues.

Closing, since it's working in my tests, but feel free to reopen with more info.

**Comment by novas1r1** [comment]
Hey @gskinner,
 
I don't know if it's related, but I'm trying to not play the animations automatically when my screen becomes visible. Therefore I defined an `AnimationController` and attached it to my object which I would like to animate. I also need to start the animation with a button click and an event so I need that controller. 

I don't know what I'm doing wrong, but it seems like I can't stop them from animating initially. Is there any other way to do this?

Here's a minimal example:

```
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
  late final AnimationController redController;
  late final AnimationController blueController;

  @override
  void initState() {
    super.initState();
    redController = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 1),
    );
    redController.stop();

    blueController = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 1),
    );
    blueController.stop();
  }

  @override
  void dispose() {
    redController.dispose();
    blueController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Demo Home Page'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.red,
                )
                    .animate(
                      controller: redController,
                      onComplete: (controller) => controller.reverse(),
                    )
                    .slideX(end: 1),
                Container(
                  width: 50,
                  height: 50,
                  color: Colors.blue,
                )
                    .animate(
                      controller: blueController,
                      onComplete: (controller) => controller.reverse(),
                    )
                    .slideX(end: -1),
              ],
            ),
            const SizedBox(height: 32),
            ElevatedButton(
                onPressed: () {
                  redController.forward(from: 0);
                },
                child: const Text('ANIMATE RED')),
            ElevatedButton(
                onPressed: () {
                  blueController.forward(from: 0);
                },
                child: const Text('ANIMATE BLUE')),
          ],
        ),
      ),
    );
  }
}

```

Thanks in advance and also thanks for providing this awesome package!

**Comment by dokumanx** [comment]
> Hey @gskinner,
> 
> I don't know if it's related, but I'm trying to not play the animations automatically when my screen becomes visible. Therefore I defined an `AnimationController` and attached it to my object which I would like to animate. I also need to start the animation with a button click and an event so I need that controller.
> 
> I don't know what I'm doing wrong, but it seems like I can't stop them from animating initially. Is there any other way to do this?
> 
> Here's a minimal example:
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:flutter_animate/flutter_animate.dart';
> 
> void main() {
>   runApp(const MyApp());
> }
> 
> class MyApp extends StatelessWidget {
>   const MyApp({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       theme: ThemeData(
>         primarySwatch: Colors.blue,
>       ),
>       home: const MyHomePage(),
>     );
>   }
> }
> 
> class MyHomePage extends StatefulWidget {
>   const MyHomePage({super.key});
> 
>   @override
>   State<MyHomePage> createState() => _MyHomePageState();
> }
> 
> class _MyHomePageState extends State<MyHomePage> with TickerProviderStateMixin {
>   late final AnimationController redController;
>   late final AnimationController blueController;
> 
>   @override
>   void initState() {
>     super.initState();
>     redController = AnimationController(
>       vsync: this,
>       duration: const Duration(seconds: 1),
>     );
>     redController.stop();
> 
>     blueController = AnimationController(
>       vsync: this,
>       duration: const Duration(seconds: 1),
>     );
>     blueController.stop();
>   }
> 
>   @override
>   void dispose() {
>     redController.dispose();
>     blueController.dispose();
>     super.dispose();
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(
>         title: const Text('Flutter Demo Home Page'),
>       ),
>       body: Padding(
>         padding: const EdgeInsets.all(8.0),
>         child: Column(
>           children: [
>             Row(
>               mainAxisAlignment: MainAxisAlignment.spaceBetween,
>               children: [
>                 Container(
>                   width: 50,
>                   height: 50,
>                   color: Colors.red,
>                 )
>                     .animate(
>                       controller: redController,
>                       onComplete: (controller) => controller.reverse(),
>                     )
>                     .slideX(end: 1),
>                 Container(
>                   width: 50,
>                   height: 50,
>                   color: Colors.blue,
>                 )
>                     .animate(
>                       controller: blueController,
>                       onComplete: (controller) => controller.reverse(),
>                     )
>                     .slideX(end: -1),
>               ],
>             ),
>             const SizedBox(height: 32),
>             ElevatedButton(
>                 onPressed: () {
>                   redController.forward(from: 0);
>                 },
>                 child: const Text('ANIMATE RED')),
>             ElevatedButton(
>                 onPressed: () {
>                   blueController.forward(from: 0);
>                 },
>                 child: const Text('ANIMATE BLUE')),
>           ],
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> Thanks in advance and also thanks for providing this awesome package!

Similar problem. I assigned a target. And everytime I open the related screen it first tries to animate but then it understands target is 0, it goes back to the initial state. And I couldn't find a way to stop it. Any idea?
