### ISSUE TITLE
ShakeEffect does not work if the duration is less than 1000 milliseconds.

### ISSUE THREAD

**Issue by ProZhar** [gskinner/flutter_animate#36]
#### Working Code

```dart
const Icon(Icons.favorite, size: 28.0)
            .animate()
            .shake(duration: 1000.ms),  // <--- work fine
```

#### NOT working Code

```dart
const Icon(Icons.favorite, size: 28.0)
            .animate()
            .shake(duration: 999.ms),  // <--- NOT work
```

I think it because `entry.duration.inSeconds` return 0 if it is less than 1000 milliseconds.

https://github.com/gskinner/flutter_animate/blob/4228b68a817f3692d3378d6748322f1cff0c2faf/lib/effects/shake_effect.dart#L64

[(Bug link)](https://github.com/gskinner/flutter_animate/blob/main/lib/effects/shake_effect.dart#L64)

**Comment by gskinner** [comment]
Good catch. Funny that I have apparently never used ShakeEffect with <1s duration. Fixed.
