### ISSUE TITLE
Restructure src files

### ISSUE THREAD

**Issue by esDotDev** [gskinner/flutter_animate#39]
Fairly minor thing, but it would be nice if the lib followed the best practices on file structure:
![image](https://user-images.githubusercontent.com/736973/201166238-45c763fe-9d84-488f-a67a-f78d1b48297a.png)

Typically the outer file, `provider.dart` in this case is the name of the lib, and exports all library classes.

Another `provider.dart` often exists inside of the `src` file, defining package level methods etc

So we'd be looking for:
```
flutter_animate.dart  // barrel file, all exports
/src
   flutter_animate.dart // global stuff like `AnimateManager` and `buildSubAnimation`
   /effects
   /adapters
   etc
```

**Comment by esDotDev** [comment]
I'm not sure if there is guidance in the docs for this (havent looked) But
all the major plugin developers have adopted this style, see Bloc,
Provider, Riverpod, GoRouter etc etc, all the same structure.

**Comment by gskinner** [comment]
Interesting. I'd love to see some rationale.

**Comment by esDotDev** [comment]
The main rationale I think is that everything in lib is public, so to keep
things clean most authors create a single library file in /lib which is
public, then everything inside /src is considered internal. Users of the
lib can then more easily determine which of your files to import cause only
one will be visible, and it exports all the others.

They talk a bit about this here, "most packages define a single library
that users can import..."
https://dart.dev/tools/pub/package-layout

**Comment by esDotDev** [comment]
Some history here: https://stackoverflow.com/a/58521728

Basically placing "implementation files" inside of /src is a recommended
convention, as it lets you easily control specific classes your pkg
considers public / importable. Also seems like there might be some
performance benefits for dev tools, as they assume this structure.

**Comment by gskinner** [comment]
Took a first stab at this here: e014260e24ee98e52585e06e04844b087b47466c

Feedback welcome.

**Comment by esDotDev** [comment]
Looks good! My only feedback would be on the `animate.dart` file.

Since it holds much more than just the `Animate` class, I'd consider
renaming `animate.dart` to `flutter_animate.dart`? This is a convention I
see a lot. An internal file "main" file, with the same name as the pkg
itself, which holds various globals, mixins, extensions, typedefs etc.
eg:
https://github.com/felangel/bloc/tree/master/packages/bloc/lib/src/bloc.dart
https://github.com/rrousselGit/provider/blob/master/lib/src/provider.dart

Or instead of renaming, could create a new file, `flutter_animate.dart` and
move all the global extensions / mixins stuff there, leaving `animate.dart`
just for the class itself which would just make things a little more
organized / discoverable.

**Comment by gskinner** [comment]
Done @esDotDev
