### ISSUE TITLE
How to reverse an animation? E.g., slideX?

### ISSUE THREAD

**Issue by buttonsrtoys** [gskinner/flutter_animate#43]
Love the package. I can make widgets slide in and get the AnimationController:

    Text.animate(onPlay: (controller) {
                  _animationController = controller;
                }).slideX(),

Is there a what to make the widget then slide out with the controller? And then back in again?

**Comment by gskinner** [comment]
The controller is just a normal `AnimationController`, so you can use any of its methods. For example, you could use`animateTo(0)` to animate it back from the end. Or if you want it to go out and back once without a pause, you could use `loop(count: 2, reverse: true)` using the loop extension method @Thithip added.

Feel free to reopen if that didn't answer your question.
