### ISSUE TITLE
[minor] Dates in changelog are wrong

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [gskinner/flutter_animate#44]
I'm pretty sure this is supposed to be 2023:
https://github.com/gskinner/flutter_animate/blob/71ace7b8ad6e4ca92c04f7d298ca3d1c70ccf2c1/CHANGELOG.md#300---2022-01-19
<img width="850" alt="image" src="https://user-images.githubusercontent.com/4954611/213621503-ad4a49cf-ee06-4689-a04e-6a3afe7e97a7.png">

**Comment by gskinner** [comment]
it's not 2023 already, is it? :)
Fixed.
