### ISSUE TITLE
Change ThenEffect to establish a new baseline time

### ISSUE THREAD

**Issue by gskinner** [gskinner/flutter_animate#45]
Currently `ThenEffect` works by establishing a new inheritable `delay`:

```
foo.animate()
  .fadeIn(duration: 700.ms) // begins at 0ms, ends at 700ms
  .then() // sets inheritable delay of 700ms (end of previous)
  .slide() // inherits 700ms delay, begins at 700ms, ends at 1400ms
  .flipX(delay: 0.ms) // overrides delay, begins at 0ms, ends at 700ms
```

It might be better if `ThenEffect` instead establishes a new "baseline time", that subsequent effects can modify with relative delays (including negative delays):

```
foo.animate()
  .fadeIn(duration: 700.ms) // begins at 0ms, ends at 700ms
  .then() // baseline is now 700ms (end of previous)
  .slide(delay: 0.ms) // begins at 700ms, ends at 1400ms
  .flipX(delay: -200.ms) // begins at 500ms, ends at 1200ms
  .then(delay: 300.ms) // baseline is now 1500ms (1200+300)
  .shake() // begins at 1500ms
```

This would require adding a new property to Animate to track this, and could break existing animations in rare cases (ex. if someone has overridden delay after using `then`).

Open to feedback on this.

**Comment by scopendo** [comment]
This seems more logical.  Presumably, a param could be added to `animate()` to allow the existing behaviour to be preserved.

**Comment by gskinner** [comment]
Thanks for the feedback!
