### ISSUE TITLE
adaptor driven animations with "delay" and "then" semantics?

### ISSUE THREAD

**Issue by RandalSchwartz** [gskinner/flutter_animate#48]
I know the adaptor is providing a 0 to 1 value, but how does that map in to the time-based effects like delay or duration or then?  It's not obvious to me how to set up what would be a time-based animation and drive it by an adaptor.  Or, if that isn't supported, could we get that supported somehow?

**Comment by gskinner** [comment]
Adapters simply map a 0-1 value to the start and end of the full animation. So for this animation:

```
foo.animate()
  .fade(duration: 700.ms) // ends at 700ms
  .then()
  .slide(duration: 500.ms) // starts at 700, ends at 1200ms
```

An adapter's `0` would map to the start (0ms) and `1` would map to the end (1200ms) — `0.5` would be 600ms.

So you can still build your animations using time, but adapters advance through that "time" based on their value.

Does that make sense?

**Comment by RandalSchwartz** [comment]
Yes, after another 30 minutes of studying the examples, it dawned on me what was going on.  Am I also correct to say that the times are somewhat arbitrary for the 0 to 1 scale, except that they're used as the actual animation time if the adaptor is told "animate: true"?

**Comment by gskinner** [comment]
You are correct. If you aren't using the `animate: true` flag, then you could use basically any values you wanted, it is only the relative ratios that would matter.

```
foo.animate().fade(duration: 1.ms).then().slide(duration: 3.ms)
```

^ That would be perfectly fine. Going to an adapter value of `0.5` would be 1/3 of the way into the slide (total time = 4ms, so 1ms into the 3ms slide).
