### ISSUE TITLE
An error is thrown by ScrollAdapter when an animated widget from ListView.builder is disposed.

### ISSUE THREAD

**Issue by indmind** [gskinner/flutter_animate#51]
I am trying to use `ScrollAdapter` inside one of the children of a `ListView.builder`, but when the widget is disposed (out of the screen) and we keep scrolling, it will throw an error.

![image](https://user-images.githubusercontent.com/29256127/215458380-7f9aaf67-c8bb-4fe1-8355-76f6cd13adde.png)

Here is the minimum reproducible example:
```dart
ListView.builder(
  controller: _scrollController,
  itemCount: 3,
  itemBuilder: (context, index) {
    final text = Text(
      index.toString(),
    );

    return SizedBox(
      height: MediaQuery.of(context).size.height,
      child: index == 0
          ? text
              .animate(adapter: ScrollAdapter(_scrollController))
              .slideY(end: 2.5)
          : text,
    );
  },
)
```
As you can see, I added an animation to the first child. When the first child goes out of view and is disposed, the error occurs.

**Comment by gskinner** [comment]
Good catch. This should be an easy fix, I'll look into it (probably today).

**Comment by gskinner** [comment]
Ok. Dug into this a bit, and it's not as easy a fix as I first thought, unless we just catch the error and call it good enough (which isn't necessarily a terrible option).

I _think_ the way I'd like to approach this is reverse the control flow by changing `Adapter` into a notifier, which `Animate` subscribes to, and then it can unsubscribe on `dispose`. This should also allow for adapters to be shared between `Animate` instances, which might be useful on occasion.

May as well also add `Adapter.enabled` while I'm at it.

**Comment by gskinner** [comment]
I just pushed a fix for this. I would really appreciate if you're able to test against this fix to confirm it's resolved in your example @indmind

**Comment by indmind** [comment]
Sorry for the late reply, I have tested the fix for the issue with using ScrollAdapter inside of a ListView, and I am happy to report that it is working as expected. Thank you, I appreciate your efforts in resolving the issue.
