### ISSUE TITLE
Animate ListView.builder [Question]

### ISSUE THREAD

**Issue by Schrolli91** [gskinner/flutter_animate#55]
Hello at all.

Is there any posibility to animate a ListView.builder in the same way,
as used for animating lists of widgets?
https://pub.dev/packages/flutter_animate#animating-lists

Thanks and best regards

**Comment by dokind** [comment]
yeah i need this too

**Comment by gskinner** [comment]
Is there a reason you wouldn't just apply the animations in your `itemBuilder`?

**Comment by Seddik-Boukhalfa** [comment]
Would'nt that apply the effects at the same time for each item in that list ? the property interval is missing at this point i guess, so we can't animate each item separately. If i missed out anything please point it out for me.

**Comment by gskinner** [comment]
All interval does is set a delay based on the index, which you can do inside itemBuilder.

Rough sketch:

```
itemBuilder: (_, i) => MyWidget().animate(delay: (i * 200).ms).fadeIn()
```

**Comment by dokind** [comment]
@gskinner thanks I will try it. 👍

**Comment by Schrolli91** [comment]
@gskinner But this will animate the items every time i scroll the view.
What i want is only an inital animation wenn the items are loaded.

but i see - not possible per default so i have to do some custom work (loading flag e.g.).
Thanks anyway for your fast reply - btw awsome lib, gthanks for that.

**Comment by Seddik-Boukhalfa** [comment]
> All interval does is set a delay based on the index, which you can do inside itemBuilder.
> 
> Rough sketch:
> 
> ```
> itemBuilder: (_, i) => MyWidget().animate(delay: (i * 200).ms).fadeIn()
> ```

Makes sense yes, thanks for the enlightenment.

**Comment by simplenotezy** [comment]
@gskinner would be awesome with an extension or way to achieve list animations in ListBuilders, while avoiding re-animating the same item list again, once it becomes visible

**Comment by s6joui** [comment]
@gskinner could we re-open this? Using the workaround of applying the animation in itemBuilder results in the animation replaying every time you scroll.
