### ISSUE TITLE
Weird behavior when widget is not `const`

### ISSUE THREAD

**Issue by mzdm** [gskinner/flutter_animate#57]
I do not have a smaller sample but below is some example where I encountered a weird error. If I don't have `Positioned` marked as `const` the hearts are not appearing at all (animation not starting). If I make it `const`, it works just fine.

Video shows how it should behave (it has hardcoded `svgImage` set to null so it can be `const`)

```dart
          if (rightButtonActive)
            /// does not animate
            Positioned(
              bottom: 105,
              right: 20,
              child: _HeartSpray(svgImage: Assets.illustrations.games.swing.rightWindHeart),
            ),
          if (leftButtonActive)
            /// works as expected, as in the video
            const Positioned(
              bottom: 105,
              left: 20,
              child: _HeartSpray(svgImage: null),
            ),
```

```dart
class _HeartSpray extends StatelessWidget {
  const _HeartSpray({required this.svgImage});

  final SvgGenImage? svgImage;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        // spawn 10 hearts
        for (var i = 0; i < 10; i++)
          Padding(
            padding: EdgeInsets.only(
              left: i.isEven ? math.Random().nextDouble() * 50 : 0,
              right: i.isEven ? 0 : math.Random().nextDouble() * 50,
            ),
            child: (svgImage ?? Assets.illustrations.games.swing.rightWindHeart)
                .svg()
                .animate(
                  delay: (i * 0.1).seconds,
                  onPlay: (controller) {
                    // repeat animation when finished
                    controller.repeat();
                  },
                )
                .fade(duration: 0.3.seconds)
                .scale(duration: 0.15.seconds)
                .slideY(begin: 1.0, end: -15, duration: 0.9.seconds)
                .shakeX(hz: 1)
                .fadeOut(delay: 0.2.seconds, duration: (0.9 - 0.4).seconds),
          ),
      ],
    );
  }
}
```

https://user-images.githubusercontent.com/67197047/216783971-be1d3cd8-4810-42a7-b224-9c91fdf6dc3e.mp4

Thanks for this package btw. Doing animations is much easier and more joyful and we can do magic stuff in just a few lines

**Comment by gskinner** [comment]
Is there any chance something is causing your content to be rebuilt (thus restarting the animation)? Perhaps the `const` is keeping that outer widget from being rebuilt? Just taking a quick guess. You could try assigning a static key to the animation to test this.

As a random aside: Based on your video, you may find my particle_field package fun as well. :)
https://pub.dev/packages/particle_field

**Comment by gskinner** [comment]
Closing for now. Feel free to reopen with more information.

**Comment by mzdm** [comment]
> Is there any chance something is causing your content to be rebuilt (thus restarting the animation)? Perhaps the `const` is keeping that outer widget from being rebuilt? Just taking a quick guess. You could try assigning a static key to the animation to test this.
> 
> As a random aside: Based on your video, you may find my particle_field package fun as well. :) https://pub.dev/packages/particle_field

Thanks, that's interesting, I did not know that there can be a such difference in the behavior with `const` widgets :O. Yes the whole screen is Stateful so the changing states probably reset the animation while when it is `const` it does not redraw
