### ISSUE TITLE
Spring animation

### ISSUE THREAD

**Issue by bernaferrari** [gskinner/flutter_animate#58]
I wish this package allowed to do something like

`UIView.animate(withDuration: 2.0, delay: (delay)/delayDivider, usingSpringWithDamping: 0.75, initialSpringVelocity: 0.5, options: .curveEaseInOut) {`

in a painless way in Flutter (source: https://github.com/danielkarath/CircularToRectangularAnimation).

Rotation + Spring is my dream.

https://twitter.com/DanielKarath/status/1614621297903812609?s=20&t=l_MDri0o7M1fBtSsJOApmg

**Comment by gskinner** [comment]
That example looks totally doable with just a Curve. You could also write a utility that generates customized spring curves from parameters. I'm not sure if that helps, but feel free to reopen with more info if not.

**Comment by bernaferrari** [comment]
Thanks for the idea! I never thought about it before! I'll explore how to make a Curve from a spring!

**Comment by gskinner** [comment]
Another way you could approach this, which I think might work is to write a `SpringAdapter` which would drive an animation with a SpringSimulation. Though the one thing that may not work properly is out of range value (ie. <0, >1).
