### ISSUE TITLE
Animate images (SVG assets)

### ISSUE THREAD

**Issue by hrithikm2** [gskinner/flutter_animate#61]
I am trying to use the flutter_svg plugin and trying to animate the images with a simple fade-in. It appears to be working fine when I hot reload the code after applying changes to the animate() extension. However, when I restart the application, the animation does not seem to work.

**Comment by gskinner** [comment]
Have you tried just swapping the SVG widget with another widget (ex. an Icon)? I'd like to be sure this is SVG specific, and not just something to do with your view setup.

**Comment by gskinner** [comment]
Closing in lieu of info. Feel free to reopen as appropriate.
