### ISSUE TITLE
Add a test or two :)

### ISSUE THREAD

**Issue by timsneath** [gskinner/flutter_animate#7]
A couple of example tests that demonstrate how to use [flutter_test](https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html) would be a great starting point. It would then be easy for others in the community to extend this to a broader list that provides good coverage for the package as a whole.

**Comment by esDotDev** [comment]
@gskinner Started on a branch here: https://github.com/gskinner/flutter_animate/pull/17

**Comment by gskinner** [comment]
We're up to at least two tests now. :)
via d3288183c9f4e45f6e14d6df7cc68b7039e92ff8

We'll keep adding coverage, but closing this as complete.
