### ISSUE TITLE
The animations are not working on mobile devices, Strange

### ISSUE THREAD

**Issue by fisforfaheem** [gskinner/flutter_animate#71]
I have attached before and after images: 
![WhatsApp Image 2023-03-07 at 5 16 40 PM](https://user-images.githubusercontent.com/35878088/223419814-a3cecec9-1003-4baf-805a-f23209ace525.jpeg)
![WhatsApp Image 2023-03-07 at 5 16 41 PM](https://user-images.githubusercontent.com/35878088/223419822-d2e88c47-6b42-47d4-8d1d-022f2c011a94.jpeg)
![WhatsApp Image 2023-03-07 at 5 16 57 PM (1)](https://user-images.githubusercontent.com/35878088/223419828-f4df3bbf-99ec-4cc8-8461-0c0805bb24a0.jpeg)
![WhatsApp Image 2023-03-07 at 5 16 57 PM](https://user-images.githubusercontent.com/35878088/223419832-ca679aa5-a0ae-4fae-902b-a5e8fa7fa60e.jpeg)
<img width="430" alt="image" src="https://user-images.githubusercontent.com/35878088/223420038-723e5591-9e48-49ad-91a4-8482dd140876.png">
<img width="626" alt="image" src="https://user-images.githubusercontent.com/35878088/223420108-2cbe113c-1f87-4059-b4a4-ce170cd3a86a.png">

**Comment by gskinner** [comment]
I'm not really sure what you're trying to communicate here. The library works on mobile, so you're going to need to provide more specific info about what's going wrong — the screenshots without context aren't sufficient.

**Comment by fisforfaheem** [comment]
by mobile I mean @gskinner flutter web, on mobile devices... the same works awesome on flutter web desktop browser but on mobile android and ios it don't show anything

**Comment by gskinner** [comment]
Ah, so the animation is working on web on desktop, but not web on mobile? That is weird, and sounds more like a Flutter issue that a library one. Have you tested a super simple use case to narrow it down (ex. just a fresh Flutter web app with nothing but some animated text)?

**Comment by fisforfaheem** [comment]
Ok will try that, and update here. I made a ton of animations for my
app...but when I ran on phone it  plainly transitions into none and black
screen.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
03/13/23,
01:58:02 AM

**Comment by nietsmmar** [comment]
I have no idea what the original poster wants to tell us with these screenshots but actually I am having the same issue.

Animations work on all devices but on my Iphone in Safari it just shows blank elements when I add an animation to a Widget. I build it with flutter `3.7.5`
