### ISSUE TITLE
Add ShaderEffect

### ISSUE THREAD

**Issue by gskinner** [gskinner/flutter_animate#72]
I have just committed a prerelease version of `ShaderEffect`, which lets you add animated fragment shaders as effects. It is currently not included in the package exports, so you will need to import it directly.

I'd really appreciate it if people can test this out, and provide feedback. I'm trying to find a balance between super easy (with shaders that use the "standardized" uniforms), and full control (via the `update` method). My hope is that people will also subclass `ShaderEffect` to create easy to use effects based on a specific shader (ex. you could imagine a `FireEffect` that exposes specific parameters like `flameColor` to manipulate its uniforms). I'm not much of a shader dev, so I'm trying to make this really easy for people who are to contribute.

This effect is fully documented. Either run `dart doc` on the package, or just peek at the [shader_effect.dart](https://github.com/gskinner/flutter_animate/blob/main/lib/src/effects/shader_effect.dart) file for full docs, but here's the ShaderEffect class docs for easy reference:

---
**NOTE: This is a prerelease shader. You must import it directly to use it.**

Effect that applies an animated fragment shader to a target. See
[Writing and using fragment shaders](https://docs.flutter.dev/development/ui/advanced/shaders)
for information on how to include shaders in your app.

[shader] is the [FragmentShader] to apply to the target. If `null` no effect
will be applied.

[overflow] defines a buffer space around the target to draw the shader. This
is useful for effects that draw outside of the target bounds, such as blurs.
Defaults to [EdgeInsets.zero].

[layer] allows you to layer the shader above, below, or completely replace
the target visually. Defaults to [ShaderLayer.replace].

[update] is an optional callback that allows you to update the shader. It
is called whenever the animation value changes. It accepts a
[ShaderUpdateDetails] object. It can update uniforms directly via
`setFloat` or `setImageSampler`, or by using [ShaderUpdateDetails.updateUniforms].

If [update] is not specified, the shader will be updated automatically based
on the "standardized" uniforms defined in [ShaderUpdateDetails.updateUniforms].

The [update] callback may return an [EdgeInsets] to define the overflow, or
`null` to use the [overflow] value.

**Comment by EdgarMagalhaes** [comment]
Hey! Awesome feature! Any plans to release this?

**Comment by gskinner** [comment]
It's included in the package already, it's just not included in the default export, so you need to import `ShaderEffect` directly. I'm going to leave this open though, as a reminder to check the current state of AnimatedSampler, and see if this should be included as a default export now.

**Comment by gskinner** [comment]
Jonah published `flutter_shaders` a while back, so I'm going to update `flutter_animate` to use it as a dependency, do some testing, and roll `ShaderEffect` in fully.

@EdgarMagalhaes & everyone — if you are using / have used `ShaderEffect`, please provide any feedback, so I know if there's anything else that should be updated / fixed prior.

Thanks!

**Comment by gskinner** [comment]
Was able to integrate the published version of `flutter_shaders` successfully, and did some documentation tweaks. Will give it a day or two for any feedback, then I'll publish 4.5.0 with this change.

**Comment by EdgarMagalhaes** [comment]
I'm currently on version 4.4.1 so I imported the ShaderEffect directly.

From what I tested so far, memory usage is going through the roof. I'm running a simple [PolkaDots](https://gl-transitions.com/editor/PolkaDotsCurtain) shader transition and the memory usage went from 200mb to almost 2gb.

This is causing iOS to kill the app due to high memory consumption. Will try your change later today to see if it solved the issue - but I guess it was a direct copy from flutter_shaders, right?

**Comment by gskinner** [comment]
Awesome! The latest release of `flutter_shaders` includes this in the changelog:

> Ensure constructed ui.Picture objects are disposed after usage.

So, I'm guessing that was the issue.

I'll likely roll this out sometime today, or maybe in the next week if I decide to tackle any other updates prior.

**Comment by gskinner** [comment]
Released. Closing.
