### ISSUE TITLE
Animations not working properly after Navigator.push

### ISSUE THREAD

**Issue by fior-di-latte** [gskinner/flutter_animate#73]
**Expected behavior:** This code should spin the Container 360° right after the Route is pushed (on click):
```
Navigator.push(
        ctx,
        MaterialPageRoute(
            builder: (_) => Container(
                  color: Colors.blue,
                  alignment: Alignment.center,
                  child: Text('Hi Animation Folks!'),
                ).animate().rotate()));
```
**Observed**: The rotation does not work. Instead there is just a flicker.

https://user-images.githubusercontent.com/30835670/228679443-c9674360-4971-49d4-90cd-4aa9cbd93918.mov

Similar things happen with any other animation right after a push.

Interestingly, when you introduce a 1 second delay `animate().rotate(delay: 1.seconds)` , everything works fine.

(Flutter 3.7.8, flutter_animate 4.1.1+1)

**Comment by gskinner** [comment]
It's been a while, but IIRC Flutter does some weird things with animation during page transitions. I think I've seen similar outcomes just using an AnimationController, so I suspect this isn't an `Animate` specific problem. If you have time to test against that, I'd appreciate it, otherwise I'll try to get to it something soon.

**Comment by bleroux** [comment]
https://github.com/flutter/flutter/issues/106621 introduced a performance improvement for zoom page transition (this is the transition Flutter uses by default on Android)
There were some trade-offs related to using animations during a transition, which is the case in this issue.

A flag was introduced to opt-out and use the previous behavior.
See https://master-api.flutter.dev/flutter/widgets/PageRoute/allowSnapshotting.html
This flag is meant to be used on a per route basis, for instance:

```dart
  Navigator.push(
    context,
    MaterialPageRoute(
      builder: (context) => const SecondRoute(),
      allowSnapshotting: false,
    ),
 );
```

On master, there is also a similar flag to disable zoom transition snapshotting globaly, see the following page for an example:
https://master-api.flutter.dev/flutter/material/ZoomPageTransitionsBuilder/allowSnapshotting.html

**Comment by fior-di-latte** [comment]
The `allowSnapshotting: false` indeed solves this problem. So no further action needed on your side!
Thanks a lot! :-)
