### ISSUE TITLE
How to perform an in and out animation

### ISSUE THREAD

**Issue by nivla360** [gskinner/flutter_animate#74]
Hello, I love this package. I have been able to animate in but I don't know how to animate out i.e. when a widget is about to be unmounted. Any help is appreciated thanks.

**Comment by elvisgn** [comment]
Voting for this feature.

Currently I added Curves.easeInOut on the effects to get the animation on mount and unmount, but more control for complex animations would be great.

Btw, awesome package.

**Comment by gskinner** [comment]
I believe this is a duplicate of #29 - please feel free to reopen with more info if not.
