### ISSUE TITLE
ScaleEffect breaks with Offset.zero and following other Effects

### ISSUE THREAD

**Issue by eggzotic** [gskinner/flutter_animate#79]
Sample project that demonstrates this issue is at: https://github.com/eggzotic/animate_demo

`ScaleEffect` misbehaves when:

- `begin == 0` *and*
- it follows other effects within `Animate`.

In the sample project above, the `ScaleEffect` always works correctly (regardless of other effects and the order in which they're specified) if `begin > 0`. This feels like a bug, as the order in which effects are listed, when run in parallel, should be irrelevant to the resulting visual experience.

https://user-images.githubusercontent.com/24584418/236104556-8afa0de1-3526-4b1b-b02e-eb83c94e2f3d.mp4

Video attached shows the behaviour - both good & bad.

**Comment by eggzotic** [comment]
Nope - just the standard stuff:

```
$ flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             17.6s
This app is linked to the debug service: ws://127.0.0.1:60718/LE7SYBDuoGY=/ws
Debug service listening on ws://127.0.0.1:60718/LE7SYBDuoGY=/ws

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:60718/LE7SYBDuoGY=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:60718/LE7SYBDuoGY=
```

And here is my flutter doctor output:

```
$ flutter doctor -v
[✓] Flutter (Channel master, 3.8.0-16.0.pre.5, on Microsoft Windows [Version 10.0.22621.1555], locale en-NZ)
    • Flutter version 3.8.0-16.0.pre.5 on channel master at C:\development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a50bdcfd18 (2 months ago), 2023-02-22 17:09:51 -0800
    • Engine revision 137caa7615
    • Dart version 3.0.0 (build 3.0.0-266.0.dev)
    • DevTools version 2.22.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\eggzo\AppData\Local\Android\sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31229.75
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[✓] VS Code (version 1.77.3)
    • VS Code at C:\Users\eggzo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.62.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 110.0.1587.63

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by gskinner** [comment]
Did some more testing:

```
Text("Playground")
            .animate(onPlay: (c) => c.repeat(reverse: true),)
            .fadeIn()
            .scaleXY(begin: 0),
```

I'm not seeing exactly what you're seeing, but I do get weird results when the scale starts at 0.

90+% of the time, the animation runs fine, but every so often the scale just won't run at all for one loop. Changing to `begin: 0.000001` seems to fully resolve it. As you suggested, removing `fadeIn` seems to resolve it, as does swapping `fadeIn` for `effect` (an empty effect).

Looking at the code, I can't see any way Animate would be causing this (we don't have any special code to deal with a scale of 0 — it's just passed through to a `Transform`), which makes me think it's some obscure Flutter issue.

I suppose I could just automatically adjust any 0 scale values up to some minimum (ex. `0.000001`). We do this for `BlurEffect` to avoid another Flutter issue. I'm always a bit hesitant to adjust incoming values, but I can't think of any significant concerns with doing so here.

Note: The tests will need to be updated as well if we do this.

**Comment by gskinner** [comment]
Guess: it occurs semi-randomly in my case because it only happens on loops where the scale hits exactly 0 (or something that's near enough to trigger the problem).
