### ISSUE TITLE
How to record animation frames

### ISSUE THREAD

**Issue by Tonku** [gskinner/flutter_animate#8]
Hi, Thanks for the awesome library, but just wondering how to capture every frame of the animation as png, so that I can create a movie?

**Comment by gskinner** [comment]
This isn't really a forum for general Flutter questions, but to point you in the right direction. Here's a post about capturing image data from Widgets:
https://medium.com/flutter-community/export-your-widget-to-image-with-flutter-dc7ecfa6bafb

To manually advance the animation position so you can capture a frame at a time (however you want to define that), you could use a `ValueAdapter` (part of Flutter Animate).
