### ISSUE TITLE
Use of target and onPlay() => repeat doesn't work?

### ISSUE THREAD

**Issue by blacroix** [gskinner/flutter_animate#85]
Hello,

I use version `flutter_animate: ^4.1.1+1`

I am trying to play a shimmer loop animation at a moment (using target). The animation runs only once if I use target, otherwise it loops properly.

Can I use target and repeat?

Code example:
```
.animate(
    target: widget.reveal ? 1 : 0, // It loops properly if I comment this line, otherwise it runs once
    onPlay: (controller) => controller.repeat(),
  )
  .shimmer(duration: 1.seconds)
  .then(delay: 500.ms),
```

**Comment by samderlust** [comment]
@blacroix  I solve the problem by using a separated `AnimationController`. 
```
.animate(controller: animatedCtrl).shimmer(
          duration: 500.ms,
        );
```

then in my `useEffect` (i'm using flutter hooks)
```
    useEffect(() {
      if (isAnimating) {
        animatedCtrl.repeat();
      } else {
        animatedCtrl.stop();
      }
      return null;
    }, [isAnimating]);```

**Comment by gskinner** [comment]
I'm not sure what you would expect to happen in the initial example? The whole point of target is to animate to a specific position in an animation and end there. Looping would negate that.

Closing this, but please feel free to add more info on what you're trying to accomplish here. Thanks!

**Comment by blacroix** [comment]
Hi, thanks for the reply.

Functionally I would like to have an infinite shimmer effect but only after a condition is met (for instance when the element is functionally revealed).

So I was trying to use `target` for waiting the condition is met and the `controller.repeat()` to have the infinite shimmer.

**Comment by bernaferrari** [comment]
Same problem. I expect to "start an animation and keep going indefinitely until the condition is false"
