### ISSUE TITLE
Support for "target" on AnimateList

### ISSUE THREAD

**Issue by Lootwig** [gskinner/flutter_animate#87]
I tried creating a PR for this, but the current API seemingly doesn't lend itself to only require a small change for this, since `AnimateList` is based on using delays, which are ignored as soon as `target` is non-null.

**Comment by gskinner** [comment]
AnimateList is really just meant as a convenience to save you a bit of code looping through widgets applying Animate to each of them. I'm hesitant to complicate it significantly to support more advanced use cases that can be handled with a loop. As such I'm going to close this, but I'm open to further discussion.

I will look at the docs for AnimateList to see if it would make sense to include a bit more info on how to approach this though.
