### ISSUE TITLE
Animate with ListView.builder()

### ISSUE THREAD

**Issue by jeremiahseun** [gskinner/flutter_animate#88]
I noticed that I cannot animate a list with an unknown number of items, unless I use List.generate.
Just that, it is usually painful after writing your perfect ListView.builder or GridView.builder or any builder list, I will have to change it to List.generate.

**Comment by redDwarf03** [comment]
Hello @jeremiahseun 
Please see my code. Perhaps it could be help you because for me it works
https://github.com/archethic-foundation/archethic-wallet/blob/9225cd7ab046ab7eade9bf54fe264a53e1cf51f1/lib/ui/views/accounts/layouts/account_list.dart#L61

**Comment by jeremiahseun** [comment]
Ooh, this is awesome. I didn't know that it would work this way.

Probably, it can be added to the README.md so that it will be visible to others. Thank you.
