### ISSUE TITLE
Linux behaviour

### ISSUE THREAD

**Issue by redDwarf03** [gskinner/flutter_animate#90]
Hello

on Linux, the render of the effects is not really good and fluid.
Do you know if we have to install a dependency or something like that to improve animation behaviour ?
Thx

**Comment by gskinner** [comment]
It's not doing anything Linux specific, so this sounds like it's a Flutter performance limitation on Linux. A quick google search for "Linux Flutter performance" returns a lot of results.

Feel free to reopen if there's something specific to Animate, or if you have ideas to improve performance there.

**Comment by gskinner** [comment]
Speak of the devil:
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6042
