### ISSUE TITLE
Animation complete callback will delay if call 'then' 

### ISSUE THREAD

**Issue by huang840801** [gskinner/flutter_animate#93]
```
.animate(onComplete: (controller){
   print("onComplete");
}, controller: AnimationController(vsync: this))
    .slideX(duration: 3000.ms, begin: 0.1, end: -0.1)
    .then(delay: 0.ms)
    .slideX(duration: 400.ms, begin: -0, end: -0.8)
```
After running animation, the console print text after 6.8s 
but if I delete `then(delay: 0.ms)` it works perfectly(print text after 3.4s) .

If I need to use chain animation and detect complete time correctly.
How to solve it

**Comment by gskinner** [comment]
Sorry for not responding to this sooner. I can confirm this issue and will look into it.

Depending on your specific use case, you may be able to use `callback` instead (or just avoid ThenEffect, using `delay` instead).

**Comment by gskinner** [comment]
Ok. I've figured out what's happening, and am working on a fix.

In brief, ThenEffect calculates it's `delay` as 3000ms (correct), and retains the 3000ms for inheritance by the next effect. This causes animate to calculate its `end` as 6000ms.

So everything is "right", it's just that ThenEffect doesn't really use duration as part of the animation, so I need to figure out if there's a safe way to exclude that.

**Comment by gskinner** [comment]
Pushed a fix. I don't love the implementation, but it should resolve this issue.
