### ISSUE TITLE
How can I prevent animation in a child widget and make the parent widget animate ?

### ISSUE THREAD

**Issue by BunnyBuddy** [gskinner/flutter_animate#98]
I am a bit new to the animation stuff and I was reluctant to use animation as its really complex in Flutter but then I stumbled upon this amazing library and I am so glad it exists. 

I'd really appreciate if I could get some guidance on how to achieve this (if possible).

Badge(
                                    toAnimate: true,
                                    animationType: BadgeAnimationType.slide,
                                    elevation: 4,
                                    shape: BadgeShape.circle,
                                    badgeColor: Colors.deepOrangeAccent,
                                    borderRadius: Get.width > 600 ? BorderRadius.circular(28.r) : BorderRadius.circular(8.r),
                                    badgeContent: Text("${Get.find<CartScreenController>().quoteCartQty.value}",
                                        style: ThemeStyles.NORMAL_STYLE_LIGHT.copyWith(color: Colors.white)),
                                    child: SvgPicture.asset(Constant.cartLogoFill, color: Colors.white),
).animate(onPlay: (con) => con.repeat(), delay: 1000.ms).shake(delay: 1000.ms),

It animates the badge and the cart logo both as a unit, but I only need the badge to animate.

**Comment by gskinner** [comment]
Any animations you apply to a parent will necessarily propagate to it's children — in Flutter the position of the parent dictates the position of the child. You could use a Stack to layer the icon over the badge though.
