### ISSUE TITLE
How to implement Staggered Animations using this library ?

### ISSUE THREAD

**Issue by sagnik-sanyal** [gskinner/flutter_animate#99]
I want to implement a staggered animation in gridview.builder or listview.builder like this https://pub.dev/packages/flutter_staggered_animations but want to use this library. Is there any way to do the same ?

**Comment by gskinner** [comment]
You can either do it manually (add delay as appropriate), or use `interval`
https://github.com/gskinner/flutter_animate#animating-lists

Feel free to reopen if this doesn't address your question.

**Comment by sagnik-sanyal** [comment]
Thanks for the info !!
